### ISSUE TITLE
Zmat.to_xyz() doc string lists incorrect return

### ISSUE THREAD

**Issue by sgill2** [mcocdawc/chemcoord#13]
Zmat.to_xyz()'s doc string says it returns a zmat when it should probably say that it returns a Cartesian.
https://github.com/mcocdawc/chemcoord/blob/master/chemcoord/zmat_functions.py#L194-L208

**Comment by mcocdawc** [comment]
Thank you very much!
It seems, I have to refactor a lot in the website backend.
I will do so in ca. two weeks.
