### ISSUE TITLE
Symbolic evaluation crashes for more than 2 assignments

### ISSUE THREAD

**Issue by Eldrad-Ulthran** [mcocdawc/chemcoord#46]
[chemcoord_subs_output_bug.txt](https://github.com/mcocdawc/chemcoord/files/1355852/chemcoord_subs_output_bug.txt)
If 1 or 2 entries of a zmatrix are replaced with a symbolic expression, the substitution back to a number is working as intended. As soon as a third entry is replaced the substitution crashes telling "can't convert expression to float". Long version of output is attached.

Code to reproduce:
```python
import chemcoord as cc
import sympy
import numpy as np
import pandas as pd
import math as m
import time
water = cc.Cartesian.read_xyz('water_dimer.xyz', start_index=1)
zwater = water.get_zmat()
symb_zwater = zwater.copy()
sympy.init_printing()
a = sympy.Symbol('a')
b = sympy.Symbol('b')
c = sympy.Symbol('c')
symb_zwater.safe_loc[4, 'dihedral'] = a
symb_zwater.safe_loc[5, 'dihedral'] = b
symb_zwater.subs(a, 180)


# (until here everything works)
symb_zwater.safe_loc[6, 'dihedral'] = c
symb_zwater.subs(a, 180)
```

(here it crashes)

#### Output of ``cc.show_versions()``

<details>
INSTALLED VERSIONS
------------------
python: 3.6.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.4-1.g4dec972-default
machine: x86_64
processor: x86_64
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

chemcoord: 1.3.0
numpy: 1.13.3
scipy: 0.19.1
pandas: 0.20.3
numba: 0.35.0
sortedcontainers: 1.5.7
sympy: 1.1.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
IPython: 5.3.0
sphinx: 1.5.6

</details>

**Comment by mcocdawc** [comment]
Thanks for the spotting.

Please have a look at: https://guides.github.com/features/mastering-markdown/ to obtain nicely formatted code. (I edited your question).

**Comment by mcocdawc** [comment]
Should work now
