### ISSUE TITLE
Numba cache bug for conda package

### ISSUE THREAD

**Issue by mcocdawc** [mcocdawc/chemcoord#55]
There are problems with the write permissions for caching numba jitted functions.
https://github.com/numba/numba/issues/1771

To further complicate things:
From my small testing this error appears only if one installs the module via conda.
With ``pip install chemcoord`` the write permissions are correctly set. 
I have no clue why it works like this.

**Comment by ghutchis** [comment]
This no longer seems to be an issue with conda. (And it seems with more recent versions of numba)

**Comment by mcocdawc** [comment]
That is great news. As soon as #75 is solved and we have a working conda-recipe and it indeed works with caching numba functions I will close this issue.
