### ISSUE TITLE
chemcoord.xyz_functions.concat

### ISSUE THREAD

**Issue by sarahkha** [mcocdawc/chemcoord#59]
I am trying to concatenate Cartesians of 2 molecules. However, the arguments are unclearly to me. Do you mind giving me an example? say I have: 
 
```
frag1 = cc.Cartesian.read_xyz('frag1.xyz', start_index=1)
frag2 = cc.Cartesian.read_xyz('frag2.xyz', start_index=1)
 
chemcoord.xyz_functions.concat(cartesians, ignore_index=False, keys=None) 
```

Thanks a lot

**Comment by mcocdawc** [comment]
Does this help?

[Concatenate_example.pdf](https://github.com/mcocdawc/chemcoord/files/3706268/Concatenate_example.pdf)
