### ISSUE TITLE
read() method from Tutorial.pynb not present

### ISSUE THREAD

**Issue by sgill2** [mcocdawc/chemcoord#6]
In your Tutorial.ipynb you use the following code to read in an xyz file:
```python
import chemcoord as cc
cc.read('some.xyz')
```
However this method doesn't seem to exist when I try to run it locally. I ended up using the following code instead to read in the xyz file:
```python
cc.xyz_functions.read_xyz('some.xyz')
````

**Comment by mcocdawc** [comment]
Thank you very much. This is a bug in the webpage.
``cc.xyz_functions.read_xyz('some.xyz')`` is the correct way to go if you installed via ``pip``.
At the moment I try to change the IO operations to a single read function.
So you will be able to write: ``cc.read(...type='xyz')``.
Somehow the tutorial of the current master branch replaced the tutorial of the v1.2.0 branch.

**Comment by sgill2** [comment]
Thanks! I'm working on some things that involves looking at internal coordinates, and I'm finding your package to be very helpful.

**Comment by mcocdawc** [comment]
Great to know, you are welcome!
I plan to continue working on the module in April so if you are missing functionality just write an Issue.

**Comment by mcocdawc** [comment]
All tutorial links point to the correct URL now
