### ISSUE TITLE
ZMAT construction

### ISSUE THREAD

**Issue by sarahkha** [mcocdawc/chemcoord#61]
Hello,

is there any function in chemcoord to construct the Zmatrix "automatically"?

Thanks 
Sarah

**Comment by mcocdawc** [comment]
There is a tutorial here:
https://chemcoord.readthedocs.io/en/v2.0.4/tutorial.html

The section Transformation gives some nice examples.

The function you are searching is:

https://chemcoord.readthedocs.io/en/v2.0.4/src_Cartesian/src_Cartesian/chemcoord.Cartesian.get_zmat.html#chemcoord.Cartesian.get_zmat

But I strongly recommend to look at the tutorial first.
