### ISSUE TITLE
get_bonds() could not define some bonds

### ISSUE THREAD

**Issue by arifin-chemist89** [mcocdawc/chemcoord#64]
Hello,

I tried to get the bonds dictionary by using the code below.

```python
xyz.get_bonds()

```
#### Problem description

I found that some of the bonds are missing. The reason is because the distance is pretty long. In my case, I have C-S bonds that where the distance are around 1.8-1.9 angstroms. 

Do you have any suggestion to solve this problem?

Thank you in advance.

**Comment by mcocdawc** [comment]
Hello,

As you probably know, there is not one single correct definition

**Comment by arifin-chemist89** [comment]
Thank you very much for your quick response.

I tried the options 1 and 2 that you mentioned above. I think I can solve my problem by using the first option. In this case, I would like to confirm that index1 corresponds to the `atom_index - 1`, isn't it?

Although this way is effective, but finding the index of the specific atoms is a bit tedious. 
Is there any way to modify the properties of a element, without adding new  columns to `constants.elements `?

**Comment by mcocdawc** [comment]
>  In this case, I would like to confirm that index1 in modified_properties = {index1: 1.5} corresponds to the atom_index - 1, isn't it?

If I use pandas terminonoly, index and label based indexing is AFAIK more or less used interchangeably. So the atom index is the label you see in the printout and can be used as is.
It is important to realize that you can use more or less any value as atom label. Even strings!
By default pandas.DataFrames and hence my classes use numbers as index.
It might help to have a look [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html) 

> Although this way is effective, but finding the index of the specific atoms is a bit tedious.
Is there any way to modify the properties of a element, without adding new columns to constants.elements?

If you want to just change one element permanently in a column, you could in theory modify this column, but I would rather copy this column and modify the copy.

**Comment by arifin-chemist89** [comment]
> If you want to just change one element permanently in a column, you could in theory modify this column, but I would rather copy this column and modify the copy.

I am completely agree with this point. Thank you very much for your comments and kind supports.
