### ISSUE TITLE
Way to generate z-matrix that doesn't conserve translational position.

### ISSUE THREAD

**Issue by p-walt** [mcocdawc/chemcoord#69]
Hi there,

Is there a way to generate a z-matrix that doesn't necessarily maintain the translational position but instead places atom 1 at the origin and sets the first few unnecessary bonds, angles in the top right triangle of the matrix to zero? Once that top right triangle is filled in can the program continue as it normally does in its generation of a logical z-matrix?

Many thanks

**Comment by mcocdawc** [comment]
Hello,

Why would you want to do this?
If you only want to consider vibrational/internal degrees of freedom, you can always just ignore the upper right triangle.
In addition I would not set them to zero, but rather to `NaN` if I understand your usecase correctly, since zero is a valid value.

**Comment by mcocdawc** [comment]
Closed because of inactivity. If you want to reopen, just comment.
