### ISSUE TITLE
Error during reading of .xyz file

### ISSUE THREAD

**Issue by p-walt** [mcocdawc/chemcoord#72]
#### Code Sample, a copy-pastable example if possible

```python
compound = cc.Cartesian.read_xyz('mm.xyz', start_index=1)
connection_table = compound.get_bonds()
```
When generating a z-matrix for a given .xyz file I receive the following warning that never previously occurred:

FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  new_frame = data.loc[atoms, set(new_cols) - set(self.columns)]
This warning is generated multiple times for each instance the function is called. 

</details>
[mm.txt](https://github.com/mcocdawc/chemcoord/files/8042396/mm.txt)

**Comment by mcocdawc** [comment]
Thank you for reporting.

May I ask what your pandas version is? I don't get that warning.

**Comment by p-walt** [comment]
Hi there,

I am currently using pandas v1.4

**Comment by mcocdawc** [comment]
I am really sorry that I somehow forgot about this issue. Will close it in the referencing one.

**Comment by mcocdawc** [comment]
Indeed it is. Thank you very much!
