### ISSUE TITLE
Adding a conda-forge recipe

### ISSUE THREAD

**Issue by ghutchis** [mcocdawc/chemcoord#75]
I ran into issues using `chemcoord` with conda-forge because the latest package in your channel is 2.0.4 and was built against older versions of numpy, etc.

I added a conda-forge recipe. The main patch was to solve character issues with the README on Windows. 🤷‍♂️ 

Do you want me to add you as a maintainer?

https://github.com/conda-forge/staged-recipes/pull/23047

**Comment by mcocdawc** [comment]
Thank you for this great help.
I would be happy to be added as maintainer as well.
If that is successful, I will remove the mention of my private `conda`  channel from the `README`; perhaps even remove it altogether.
There should be only one source of truth. :-)

**Comment by ghutchis** [comment]
Okay, I added you as maintainer. I don't know how long it takes to merge the recipe, but it should be easier to keep up-to-date with future releases.

**Comment by mcocdawc** [comment]
Perfect, thank you very much

**Comment by mcocdawc** [comment]
Until the conda-forge recipe is not merged, I removed installation via `conda` from the README.

**Comment by ghutchis** [comment]
This is now finished:
https://anaconda.org/conda-forge/chemcoord

**Comment by mcocdawc** [comment]
Thank you very much for your help!

**Comment by mcocdawc** [comment]
PS: In the next iteration I will add you to the list of contributors. (Unless you object of course.)
